# TCL File Generated by Component Editor 12.1
# Wed Jul 09 19:10:10 CEST 2014
# DO NOT MODIFY


# 
# distancecore "distancecore" v1.0
# null 2014.07.09.19:10:10
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module distancecore
# 
set_module_property NAME distancecore
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME distancecore
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL distancecore
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file distancecore.vhd VHDL PATH synthesis/submodules/distancecore.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock Clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master chipselect chipselect Output 1
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master address address Output 16
add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master writedata writedata Output 32
add_interface_port avalon_master waitrequest waitrequest Input 1


# 
# connection point NDim
# 
add_interface NDim conduit end
set_interface_property NDim associatedClock clock
set_interface_property NDim associatedReset ""
set_interface_property NDim ENABLED true

add_interface_port NDim NDim export Input 8


# 
# connection point Cl
# 
add_interface Cl conduit end
set_interface_property Cl associatedClock clock
set_interface_property Cl associatedReset ""
set_interface_property Cl ENABLED true

add_interface_port Cl Cl export Output 4


# 
# connection point Go
# 
add_interface Go conduit end
set_interface_property Go associatedClock clock
set_interface_property Go associatedReset ""
set_interface_property Go ENABLED true

add_interface_port Go Go export Input 1


# 
# connection point EndComp
# 
add_interface EndComp conduit end
set_interface_property EndComp associatedClock clock
set_interface_property EndComp associatedReset ""
set_interface_property EndComp ENABLED true

add_interface_port EndComp EndComp export Output 1


# 
# connection point NTr
# 
add_interface NTr conduit end
set_interface_property NTr associatedClock clock
set_interface_property NTr associatedReset ""
set_interface_property NTr ENABLED true

add_interface_port NTr NTr export Input 8


# 
# connection point Full
# 
add_interface Full conduit end
set_interface_property Full associatedClock clock
set_interface_property Full associatedReset ""
set_interface_property Full ENABLED true

add_interface_port Full Full export Input 1


# 
# connection point Empty
# 
add_interface Empty conduit end
set_interface_property Empty associatedClock clock
set_interface_property Empty associatedReset ""
set_interface_property Empty ENABLED true

add_interface_port Empty Empty export Output 1


# 
# connection point EndTSetIn
# 
add_interface EndTSetIn conduit end
set_interface_property EndTSetIn associatedClock clock
set_interface_property EndTSetIn associatedReset ""
set_interface_property EndTSetIn ENABLED true

add_interface_port EndTSetIn EndTSetIn export Input 1


# 
# connection point EndTSetOut
# 
add_interface EndTSetOut conduit end
set_interface_property EndTSetOut associatedClock clock
set_interface_property EndTSetOut associatedReset ""
set_interface_property EndTSetOut ENABLED true

add_interface_port EndTSetOut EndTSetOut export Output 1


# 
# connection point DistReset
# 
add_interface DistReset conduit end
set_interface_property DistReset associatedClock clock
set_interface_property DistReset associatedReset ""
set_interface_property DistReset ENABLED true

add_interface_port DistReset reset export Input 1


# 
# connection point Drop
# 
add_interface Drop conduit end
set_interface_property Drop associatedClock clock
set_interface_property Drop associatedReset ""
set_interface_property Drop ENABLED true

add_interface_port Drop Drop export Input 1


# 
# connection point avalon_master_1
# 
add_interface avalon_master_1 avalon start
set_interface_property avalon_master_1 addressUnits SYMBOLS
set_interface_property avalon_master_1 associatedClock clock
set_interface_property avalon_master_1 associatedReset reset
set_interface_property avalon_master_1 bitsPerSymbol 8
set_interface_property avalon_master_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_1 burstcountUnits WORDS
set_interface_property avalon_master_1 doStreamReads false
set_interface_property avalon_master_1 doStreamWrites false
set_interface_property avalon_master_1 holdTime 0
set_interface_property avalon_master_1 linewrapBursts false
set_interface_property avalon_master_1 maximumPendingReadTransactions 0
set_interface_property avalon_master_1 readLatency 0
set_interface_property avalon_master_1 readWaitTime 1
set_interface_property avalon_master_1 setupTime 0
set_interface_property avalon_master_1 timingUnits Cycles
set_interface_property avalon_master_1 writeWaitTime 0
set_interface_property avalon_master_1 ENABLED true

add_interface_port avalon_master_1 waitrequest1 waitrequest Input 1
add_interface_port avalon_master_1 chipselect1 chipselect Output 1
add_interface_port avalon_master_1 read1 read Output 1
add_interface_port avalon_master_1 write1 write Output 1
add_interface_port avalon_master_1 address1 address Output 16
add_interface_port avalon_master_1 readdata1 readdata Input 32
add_interface_port avalon_master_1 writedata1 writedata Output 32


# 
# connection point QAddress
# 
add_interface QAddress conduit end
set_interface_property QAddress associatedClock clock
set_interface_property QAddress associatedReset ""
set_interface_property QAddress ENABLED true

add_interface_port QAddress QAddress export Input 16


# 
# connection point SkipAddr
# 
add_interface SkipAddr conduit end
set_interface_property SkipAddr associatedClock clock
set_interface_property SkipAddr associatedReset ""
set_interface_property SkipAddr ENABLED true

add_interface_port SkipAddr SkipAddr export Input 16


# 
# connection point Dist
# 
add_interface Dist conduit end
set_interface_property Dist associatedClock clock
set_interface_property Dist associatedReset ""
set_interface_property Dist ENABLED true

add_interface_port Dist Dist export Output 16


# 
# connection point Overflow
# 
add_interface Overflow conduit end
set_interface_property Overflow associatedClock clock
set_interface_property Overflow associatedReset ""
set_interface_property Overflow ENABLED true

add_interface_port Overflow Overflow export Output 1

