# TCL File Generated by Component Editor 12.1
# Tue Jun 03 09:50:35 CEST 2014
# DO NOT MODIFY


# 
# NDimReg "NDimReg" v1.0
# null 2014.06.03.09:50:35
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module NDimReg
# 
set_module_property NAME NDimReg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME NDimReg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL NDimReg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ndimreg.vhd VHDL PATH synthesis/submodules/ndimreg.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point NDim0
# 
add_interface NDim0 conduit end
set_interface_property NDim0 associatedClock clock
set_interface_property NDim0 associatedReset ""
set_interface_property NDim0 ENABLED true

add_interface_port NDim0 NDim0 export Output 8


# 
# connection point NDim1
# 
add_interface NDim1 conduit end
set_interface_property NDim1 associatedClock clock
set_interface_property NDim1 associatedReset ""
set_interface_property NDim1 ENABLED true

add_interface_port NDim1 NDim1 export Output 8


# 
# connection point NDim2
# 
add_interface NDim2 conduit end
set_interface_property NDim2 associatedClock clock
set_interface_property NDim2 associatedReset ""
set_interface_property NDim2 ENABLED true

add_interface_port NDim2 NDim2 export Output 8


# 
# connection point NDim3
# 
add_interface NDim3 conduit end
set_interface_property NDim3 associatedClock clock
set_interface_property NDim3 associatedReset ""
set_interface_property NDim3 ENABLED true

add_interface_port NDim3 NDim3 export Output 8

